import type { TutorialStep } from "./types";

/**
 * The 26-step GreenFlow product walkthrough (spec §8), mapped to the real routes
 * and data-tour-id selectors. Every anchored step is interactive — the
 * spotlighted region stays usable — and `hint` gives a "try it" cue. Steps with
 * no `target` render as a centered card.
 */
export const tutorialSteps: TutorialStep[] = [
  // ---------------- Chapter 1 — Observe: Dashboard & 3D View ----------------
  {
    id: "welcome",
    chapter: "observe",
    route: "/dashboard",
    title: "Welcome to GreenFlow",
    body: "GreenFlow lets operators see building performance, inspect the digital twin, run risk-controlled optimization, and validate energy impact. This tour is hands-on — try things as you go.",
    placement: "center",
    before: [{ type: "switchTab", route: "/dashboard" }, { type: "stopAgentPreview" }, { type: "setElectricalShowcase", on: false }],
  },
  {
    id: "dashboard-health-index",
    chapter: "observe",
    route: "/dashboard",
    target: "dashboard-health-index",
    title: "Building Performance Index",
    body: "This view summarizes the building across air quality, energy & load demand, thermal comfort, and equipment health. Higher scores mean better operating condition.",
    placement: "bottom",
    chips: ["Air Quality", "Energy", "Comfort", "Equipment"],
    hint: "Hover a card's ⓘ to see how each score is derived.",
  },
  {
    id: "digital-twin-viewer",
    chapter: "observe",
    route: "/dashboard",
    target: "digital-twin-viewer",
    title: "The 3D Digital Twin",
    body: "The digital twin turns BIM and operational data into an explorable model — from whole-building context down to a single zone.",
    placement: "left",
    hint: "Drag to orbit · scroll to zoom the model.",
    before: [
      { type: "setLayers", layers: { architecture: false, spaces: false, fenestration: false, structural: true, hvac: false, electrical: false } },
      { type: "setHeatmap", heatmap: "electrical", enabled: false },
      { type: "setHeatmap", heatmap: "hvac", enabled: false },
      { type: "clearZone" },
      { type: "setCamera", preset: "building-overview" },
    ],
  },
  {
    id: "digital-twin-layers",
    chapter: "observe",
    route: "/dashboard",
    target: "digital-twin-layers",
    title: "Explore by Layer",
    body: "Layers separate architecture, structure, electrical, HVAC and spaces. Watch them combine automatically, then mix your own.",
    placement: "right",
    hint: "The layers are cycling — tick any box to override.",
    before: [{ type: "showcaseLayers" }],
  },
  {
    id: "system-heatmaps",
    chapter: "observe",
    route: "/dashboard",
    target: "system-heatmaps",
    title: "System Heatmaps",
    body: "Technical systems show their own heatmaps — electrical load percentage and HVAC power — keeping system-level risk separate from zone comfort scores.",
    placement: "left",
    hint: "Toggle the Electrical / HVAC heatmaps to compare.",
    before: [
      { type: "setLayer", layer: "electrical", enabled: true },
      { type: "setLayer", layer: "hvac", enabled: true },
      { type: "setHeatmap", heatmap: "electrical", enabled: true },
      { type: "setHeatmap", heatmap: "hvac", enabled: true },
    ],
  },
  {
    id: "zone-inspector",
    chapter: "observe",
    route: "/dashboard",
    target: "zone-inspector",
    title: "Inspect a Zone",
    body: "Selecting a zone opens its technical state: temperature, setpoint, occupancy, load, HVAC, lighting, area, comfort status and peak risk.",
    placement: "left",
    hint: "Click different zones in the 3D model to compare them.",
    before: [
      { type: "setHeatmap", heatmap: "electrical", enabled: false },
      { type: "setHeatmap", heatmap: "hvac", enabled: false },
      { type: "setLayers", layers: { architecture: false, spaces: true, fenestration: false, structural: true, hvac: false, electrical: false } },
      { type: "selectZone" },
      { type: "setCamera", preset: "zone-focus" },
    ],
  },
  {
    id: "cctv-occupancy-preview",
    chapter: "observe",
    route: "/dashboard",
    target: "cctv-occupancy-preview",
    title: "CCTV Occupancy Intelligence",
    body: "GreenFlow can estimate real-time occupancy from CCTV using computer vision, so the control system understands how the building is actually being used.",
    placement: "left",
  },
  {
    id: "zone-state-table",
    chapter: "observe",
    route: "/dashboard",
    target: "zone-state-table",
    title: "Zone Table & Filtering",
    body: "The zone table turns 3D context into an operational list — sort and filter zones by occupancy, temperature, load, comfort and peak risk.",
    placement: "top",
    hint: "Search or filter by type / comfort / peak risk.",
    before: [{ type: "setCamera", preset: "building-overview" }],
  },
  {
    id: "weather-context-panel",
    chapter: "observe",
    route: "/dashboard",
    target: "weather-context-panel",
    title: "Weather & External Context",
    body: "External weather drives cooling demand, comfort risk and peak load, so GreenFlow keeps weather context next to the building view.",
    placement: "top",
    chips: ["Outdoor temp", "Humidity", "Solar", "Heat stress"],
  },

  // ---------------- Chapter 2 — Understand: Electrical Graph ----------------
  {
    id: "electrical-kpis",
    chapter: "understand",
    route: "/electrical",
    target: "electrical-kpis",
    title: "Electrical Distribution Twin",
    body: "The Electrical Twin summarizes energy, cost, peak demand, emissions intensity, load risk, system mix and the top consuming zones.",
    placement: "bottom",
    before: [
      { type: "switchTab", route: "/electrical" },
      { type: "setElectricalShowcase", on: true },
      { type: "setElectricalColorMode", mode: "status" },
      { type: "focusElectricalBoard", which: "clear" },
      { type: "setElectricalLinks", on: true },
    ],
  },
  {
    id: "electrical-graph-canvas",
    chapter: "understand",
    route: "/electrical",
    target: "electrical-graph-canvas",
    title: "Distribution Graph",
    body: "The 3D graph shows how power moves from distribution boards through circuits to the connected loads across every floor. It slowly orbits so you can read the topology.",
    placement: "left",
    hint: "Drag to orbit · scroll to zoom · click a board.",
  },
  {
    id: "electrical-node-inspector",
    chapter: "understand",
    route: "/electrical",
    target: "electrical-node-inspector",
    title: "Panel-Level Distribution",
    body: "We isolated the main board: its supply lines and served zones stay lit while the rest dims — this is exactly how one panel is distributed downstream.",
    placement: "left",
    hint: "Click any other board to isolate it instead.",
    before: [
      { type: "setElectricalColorMode", mode: "feeder" },
      { type: "setElectricalLinks", on: true },
      { type: "focusElectricalBoard", which: "top" },
    ],
  },
  {
    id: "electrical-filter-controls",
    chapter: "understand",
    route: "/electrical",
    target: "electrical-filter-controls",
    title: "Filters & Load Heat",
    body: "Overload, Feeder and Load-heat recolour the model; supply lines can be toggled on and off; floors, zones and loads filter what's shown. The view is now in Load-heat.",
    placement: "bottom",
    hint: "Try Overload / Feeder / Load heat and toggle Links.",
    before: [
      { type: "focusElectricalBoard", which: "clear" },
      { type: "setElectricalColorMode", mode: "load" },
      { type: "setElectricalLinks", on: true },
    ],
  },
  {
    id: "ai-chatbot-panel",
    chapter: "understand",
    route: "/electrical",
    target: "ai-chatbot-panel",
    title: "Ask the Building Copilot",
    body: "Operators can ask for insight by text or voice. The copilot answers from the live digital twin, not from generic assumptions.",
    placement: "left",
    hint: "Type a question, e.g. \"What is the peak load today?\"",
    before: [{ type: "setElectricalShowcase", on: false }, { type: "openChatbot", open: true }],
    after: [{ type: "openChatbot", open: false }],
  },

  // ---------------- Chapter 3 — Optimize: Agents & Actions ----------------
  {
    id: "agent-main-chat",
    chapter: "optimize",
    route: "/agent-actions",
    target: "agent-main-chat",
    title: "The Agent Workspace",
    body: "This tab is where GreenFlow explains what it sees, proposes actions, and shows the reasoning behind every decision.",
    placement: "left",
    before: [{ type: "switchTab", route: "/agent-actions" }, { type: "setElectricalShowcase", on: false }, { type: "stopAgentPreview" }],
  },
  {
    id: "run-optimization-button",
    chapter: "optimize",
    route: "/agent-actions",
    target: "run-optimization-button",
    title: "Run a Safe Optimization",
    body: "Run Optimization starts a risk-controlled workflow. In tutorial mode this is a preview only — it never executes real building controls.",
    placement: "bottom",
    hint: "Click Run Optimization to launch the preview.",
    after: [{ type: "startAgentPreview" }],
  },
  {
    id: "simulation-agent-block",
    chapter: "optimize",
    route: "/agent-actions",
    target: "simulation-agent-block",
    title: "Building Semantic Agent",
    body: "The Building Semantic Agent reads the current timestep — zones, devices, abnormal findings, heatmaps and semantic-graph relationships.",
    placement: "right",
    hint: "Toggle ELEC / HVAC / Heatmap in the 3D preview.",
    before: [{ type: "startAgentPreview" }],
  },
  {
    id: "prediction-agent-block",
    chapter: "optimize",
    route: "/agent-actions",
    target: "prediction-agent-block",
    title: "Prediction Agent",
    body: "The Prediction Agent forecasts demand, peak-load zones and comfort risk, so the system can act before problems become expensive.",
    placement: "right",
  },
  {
    id: "control-agent-block",
    chapter: "optimize",
    route: "/agent-actions",
    target: "control-agent-block",
    title: "Control Agent",
    body: "The Control Agent compares the predictions and builds candidate control trajectories for the next 8 timesteps.",
    placement: "right",
  },
  {
    id: "policy-engine-block",
    chapter: "optimize",
    route: "/agent-actions",
    target: "policy-engine-block",
    title: "Simulation & Policy Gate",
    body: "GreenFlow never applies actions blindly. It simulates the top-k plans, checks policy constraints, and only forwards approved candidates.",
    placement: "right",
  },
  {
    id: "action-queue",
    chapter: "optimize",
    route: "/agent-actions",
    target: "action-queue",
    title: "Human Approval Queue",
    body: "Actions that affect real operation wait for human approval — each with estimated savings, peak reduction, comfort impact and an audit trail. Approve/Reject are disabled in the tour.",
    placement: "left",
    after: [{ type: "stopAgentPreview" }],
  },

  // ---------------- Chapter 4 — Validate: Validation Experiment ----------------
  {
    id: "validation-summary-cards",
    chapter: "validate",
    route: "/simulation-baseline",
    target: "validation-summary-cards",
    title: "Validation Experiment",
    body: "The Validation tab compares baseline operation with GreenFlow optimization on recorded 2024 data — impact is measured here, not just claimed.",
    placement: "bottom",
    before: [{ type: "switchTab", route: "/simulation-baseline" }, { type: "stopAgentPreview" }],
  },
  {
    id: "validation-el-nino-toggle",
    chapter: "validate",
    route: "/simulation-baseline",
    target: "validation-el-nino-toggle",
    title: "Severe Climate Context",
    body: "The El Niño overlay shows how the system responds under heat stress, when cooling demand and peak pressure become more severe.",
    placement: "bottom",
    hint: "Tick El Niño, or switch the metric to compare.",
    before: [{ type: "setValidationMetric", metric: "energy" }, { type: "toggleElNino", on: true }],
  },
  {
    id: "validation-impact-metrics",
    chapter: "validate",
    route: "/simulation-baseline",
    target: "validation-summary-cards",
    title: "Operational Impact",
    body: "GreenFlow translates control performance into outcomes: less wasted energy, lower indirect emissions, reduced grid pressure and longer asset life.",
    placement: "bottom",
    chips: ["Energy saved", "CO₂ avoided", "Peak reduction", "Comfort: 0 min"],
  },
  {
    id: "building-semantic-report",
    chapter: "validate",
    route: "/simulation-baseline",
    target: "building-semantic-report-button",
    title: "Generate a Monthly Report",
    body: "Finally, operators can generate a monthly building performance report for internal review, ESG reporting or stakeholder communication.",
    placement: "bottom",
    blockInteraction: true,
  },
  {
    id: "completion",
    chapter: "validate",
    route: "/simulation-baseline",
    title: "You've seen the GreenFlow loop",
    body: "Observe the building, understand the electrical twin, optimize through risk-controlled agents, and validate the impact. You're ready to explore.",
    placement: "center",
  },
];

export const TUTORIAL_STEP_COUNT = tutorialSteps.length;
