import type { TutorialStep } from "./types";

const IMG = {
  bimSingapore: "/assets/buildings/BIM_singapore.png",
  realBuilding: "/assets/buildings/real_building.png",
  constructBot: "/assets/landing/chatbot/construct_bot.png",
  elNino: "/assets/landing/chatbot/el_nino_2024.png",
  kwhBot: "/assets/landing/chatbot/kwh_bot.png",
  co2Bot: "/assets/landing/chatbot/co2_bot.png",
  peakBot: "/assets/landing/chatbot/peak_bot.png",
  expantancyBot: "/assets/landing/chatbot/expantancy_bot.png",
};

/**
 * GreenFlow product walkthrough, mapped to the real routes + data-tour-id
 * selectors. Every anchored step is interactive; copy is kept short. `media`
 * adds floating illustration cards; `spotlights` boxes extra elements.
 */
export const tutorialSteps: TutorialStep[] = [
  // ---------------- Chapter 1 — Observe: Dashboard & 3D View ----------------
  {
    id: "welcome",
    chapter: "observe",
    route: "/dashboard",
    title: "Welcome to GreenFlow",
    body: "See the building, inspect the digital twin, run safe optimization, and validate the impact. This tour is hands-on — try things as you go.",
    placement: "center",
    before: [
      { type: "switchTab", route: "/dashboard" },
      { type: "stopAgentPreview" },
      { type: "setElectricalShowcase", on: false },
      { type: "setViewerSpin", on: false },
    ],
  },
  {
    id: "dashboard-health-index",
    chapter: "observe",
    route: "/dashboard",
    target: "dashboard-health-index",
    title: "Building Performance Index",
    body: "One glance at air quality, energy & load, thermal comfort and equipment health. Higher is better.",
    placement: "bottom",
    chips: ["Air Quality", "Energy", "Comfort", "Equipment"],
  },
  {
    id: "digital-twin-viewer",
    chapter: "observe",
    route: "/dashboard",
    target: "digital-twin-viewer",
    title: "The 3D Digital Twin",
    body: "BIM + live operational data become one explorable model — whole-building down to a single zone.",
    placement: "left",
    hint: "Drag to orbit · scroll to zoom.",
    media: [{
      src: IMG.bimSingapore, variant: "card", anchor: "top-right", width: 430,
      caption: "Singapore's Building & Construction Authority (BCA) uses BIM as a national digital foundation — for coordinated 3D models, regulatory approval and lifecycle building management.",
    }],
    before: [
      { type: "setLayers", layers: { architecture: false, spaces: false, fenestration: false, structural: true, hvac: false, electrical: false } },
      { type: "setHeatmap", heatmap: "electrical", enabled: false },
      { type: "setHeatmap", heatmap: "hvac", enabled: false },
      { type: "clearZone" },
      { type: "setCamera", preset: "building-overview" },
      { type: "setViewerSpin", on: true },
    ],
  },
  {
    id: "digital-twin-real",
    chapter: "observe",
    route: "/dashboard",
    target: "digital-twin-viewer",
    title: "Twin ↔ Real Building",
    body: "Every zone maps to the real building — same offices, plant and facade, kept in sync with live data.",
    placement: "left",
    media: [
      { src: IMG.constructBot, variant: "float", anchor: "top-right", width: 300 },
      { src: IMG.realBuilding, variant: "card", anchor: "bottom-right", width: 540 },
    ],
    before: [{ type: "setViewerSpin", on: true }],
  },
  {
    id: "digital-twin-layers",
    chapter: "observe",
    route: "/dashboard",
    target: "digital-twin-viewer",
    title: "Explore by Layer",
    body: "Architecture, structure, electrical, HVAC and spaces — watch them combine, then mix your own.",
    placement: "right",
    hint: "The frame is cycling layers — tick a box to override.",
    before: [{ type: "setViewerSpin", on: false }, { type: "showcaseLayers" }],
  },
  {
    id: "system-heatmaps",
    chapter: "observe",
    route: "/dashboard",
    target: "digital-twin-viewer",
    title: "System Heatmaps",
    body: "Electrical load % and HVAC power get their own heatmaps, separate from zone comfort scores.",
    placement: "left",
    hint: "Toggle the Electrical / HVAC heatmaps.",
    before: [
      { type: "setViewerSpin", on: false },
      { type: "setLayers", layers: { architecture: true, spaces: false, fenestration: true, structural: false, hvac: true, electrical: true } },
      { type: "setHeatmap", heatmap: "electrical", enabled: true },
      { type: "setHeatmap", heatmap: "hvac", enabled: true },
      { type: "setCamera", preset: "technical-stack" },
    ],
  },
  {
    id: "zone-inspector",
    chapter: "observe",
    route: "/dashboard",
    target: "zone-inspector",
    title: "Inspect a Zone",
    body: "Temperature, setpoint, occupancy, load, HVAC, lighting, comfort and peak risk — per zone.",
    placement: "left",
    hint: "Click different zones in the model to compare.",
    before: [
      { type: "setHeatmap", heatmap: "electrical", enabled: false },
      { type: "setHeatmap", heatmap: "hvac", enabled: false },
      { type: "setLayers", layers: { architecture: true, spaces: true, fenestration: true, structural: false, hvac: false, electrical: false } },
      { type: "selectZone" },
      { type: "setCamera", preset: "zone-focus" },
    ],
  },
  {
    id: "cctv-occupancy-preview",
    chapter: "observe",
    route: "/dashboard",
    target: "cctv-occupancy-preview",
    title: "CCTV Occupancy",
    body: "Computer vision estimates real-time occupancy from CCTV, so control knows how the space is used.",
    placement: "left",
  },
  {
    id: "zone-state-table",
    chapter: "observe",
    route: "/dashboard",
    target: "zone-state-table",
    scrollBlock: "end",
    spotlights: ["digital-twin-viewer"],
    title: "Zone Table & Filtering",
    body: "The 3D context becomes an operational list — the selection syncs live between the model and the table.",
    placement: "top",
    hint: "Sort or filter by type / comfort / peak risk.",
    before: [
      { type: "setViewerSpin", on: false },
      { type: "setLayers", layers: { architecture: true, spaces: true, fenestration: true, structural: false, hvac: false, electrical: false } },
      { type: "setCamera", preset: "building-overview" },
      { type: "cycleZones" },
    ],
  },
  {
    id: "weather-context-panel",
    chapter: "observe",
    route: "/dashboard",
    target: "weather-context-panel",
    title: "Weather Context",
    body: "Outdoor conditions drive cooling demand, comfort risk and peak load — kept next to the building view.",
    placement: "top",
    before: [{ type: "clearZone" }],
  },

  // ---------------- Chapter 2 — Understand: Electrical Graph ----------------
  {
    id: "go-to-electrical-tab",
    chapter: "understand",
    route: "/dashboard",
    target: "nav-electrical-graph",
    title: "Next: Electrical Graph",
    body: "See how power is distributed through the building.",
    placement: "right",
    hint: "Click the Electrical Graph tab.",
  },
  {
    id: "electrical-kpis",
    chapter: "understand",
    route: "/electrical",
    target: "electrical-kpis",
    title: "Electrical Distribution Twin",
    body: "Energy, cost, peak demand, emissions, load risk, system mix and the top consuming zones.",
    placement: "bottom",
    before: [
      { type: "setElectricalShowcase", on: false },
      { type: "setElectricalColorMode", mode: "status" },
      { type: "focusElectricalBoard", which: "clear" },
      { type: "setElectricalLinks", on: true },
    ],
  },
  {
    id: "electrical-graph-canvas",
    chapter: "understand",
    route: "/electrical",
    target: "electrical-graph-canvas",
    title: "Distribution Graph",
    body: "Power flows from boards through circuits to the loads on every floor. The view slowly orbits.",
    placement: "left",
    hint: "Drag to orbit · click a board.",
    before: [
      { type: "setElectricalShowcase", on: true },
      { type: "setElectricalColorMode", mode: "feeder" },
      { type: "setElectricalLinks", on: true },
      { type: "focusElectricalBoard", which: "top" },
    ],
  },
  {
    id: "electrical-node-inspector",
    chapter: "understand",
    route: "/electrical",
    target: "electrical-graph-canvas",
    title: "One Panel, Distributed",
    body: "We isolated the main board — its supply lines and served zones stay lit while the rest dims.",
    placement: "left",
    hint: "Click another board to isolate it.",
    before: [
      { type: "setElectricalColorMode", mode: "feeder" },
      { type: "setElectricalLinks", on: true },
      { type: "focusElectricalBoard", which: "top" },
    ],
  },
  {
    id: "electrical-filter-controls",
    chapter: "understand",
    route: "/electrical",
    target: "electrical-graph-canvas",
    title: "Filters & Load Heat",
    body: "Overload, Feeder and Load-heat recolour the model; links toggle on/off. It's on Load heat now.",
    placement: "left",
    hint: "Try the color modes and Links toggle.",
    before: [
      { type: "setElectricalShowcase", on: true },
      { type: "setElectricalColorMode", mode: "load" },
      { type: "focusElectricalBoard", which: "clear" },
      { type: "setElectricalLinks", on: true },
    ],
  },
  {
    id: "ai-chatbot-panel",
    chapter: "understand",
    route: "/electrical",
    target: "ai-chatbot-panel",
    title: "Ask the Copilot",
    body: "Ask by text or voice — the copilot answers from the live twin, not generic assumptions.",
    placement: "left",
    hint: "Try: \"What is the peak load today?\"",
    before: [{ type: "setElectricalShowcase", on: false }, { type: "openChatbot", open: true }],
    after: [{ type: "openChatbot", open: false }],
  },

  // ---------------- Chapter 3 — Optimize: Agents & Actions ----------------
  {
    id: "go-to-agents-tab",
    chapter: "optimize",
    route: "/electrical",
    target: "nav-agents-actions",
    title: "Next: Agents & Actions",
    body: "See how observations become safe optimization proposals.",
    placement: "right",
    hint: "Click the Agents & Actions tab.",
    before: [{ type: "setElectricalShowcase", on: false }, { type: "focusElectricalBoard", which: "clear" }],
  },
  {
    id: "agent-main-chat",
    chapter: "optimize",
    route: "/agent-actions",
    target: "agent-main-chat",
    title: "The Agent Workspace",
    body: "Where GreenFlow explains what it sees, proposes actions, and shows its reasoning.",
    placement: "left",
    before: [{ type: "setElectricalShowcase", on: false }, { type: "stopAgentPreview" }],
  },
  {
    id: "run-optimization-button",
    chapter: "optimize",
    route: "/agent-actions",
    target: "run-optimization-button",
    title: "Run a Safe Optimization",
    body: "Starts a risk-controlled workflow. In the tour it's a preview — no real controls execute.",
    placement: "bottom",
    hint: "Click Run Optimization.",
    after: [{ type: "startAgentPreview" }],
  },
  {
    id: "simulation-agent-block",
    chapter: "optimize",
    route: "/agent-actions",
    target: "simulation-agent-block",
    title: "Building Semantic Agent",
    body: "Reads the current timestep — zones, devices, findings, heatmaps and graph relationships.",
    placement: "right",
    hint: "Toggle ELEC / HVAC in the 3D preview.",
    before: [{ type: "startAgentPreview" }],
  },
  {
    id: "prediction-agent-block",
    chapter: "optimize",
    route: "/agent-actions",
    target: "prediction-agent-block",
    title: "Prediction Agent",
    body: "Forecasts demand, peak-load zones and comfort risk — so the system can act early.",
    placement: "right",
  },
  {
    id: "control-agent-block",
    chapter: "optimize",
    route: "/agent-actions",
    target: "control-agent-block",
    title: "Control Agent",
    body: "Builds candidate control trajectories for the next 8 timesteps.",
    placement: "right",
  },
  {
    id: "policy-engine-block",
    chapter: "optimize",
    route: "/agent-actions",
    target: "policy-engine-block",
    title: "Simulation & Policy Gate",
    body: "Simulates the top-k plans, checks constraints, and only forwards approved candidates.",
    placement: "right",
  },
  {
    id: "action-queue",
    chapter: "optimize",
    route: "/agent-actions",
    target: "action-queue",
    title: "Human Approval Queue",
    body: "Real actions wait for a human — each with savings, peak, comfort impact and an audit trail.",
    placement: "left",
    after: [{ type: "stopAgentPreview" }],
  },

  // ---------------- Chapter 4 — Validate: Validation Experiment ----------------
  {
    id: "go-to-validation-tab",
    chapter: "validate",
    route: "/agent-actions",
    target: "nav-validation",
    title: "Next: Validation",
    body: "Prove the strategy actually improves operation.",
    placement: "right",
    hint: "Click the Validation tab.",
    before: [{ type: "stopAgentPreview" }],
  },
  {
    id: "validation-summary-cards",
    chapter: "validate",
    route: "/simulation-baseline",
    target: "validation-summary-cards",
    title: "Validation Experiment",
    body: "Baseline vs GreenFlow optimization on recorded 2024 data — impact measured, not claimed.",
    placement: "bottom",
    before: [{ type: "stopAgentPreview" }, { type: "setValidationMetric", metric: "energy" }],
  },
  {
    id: "validation-el-nino-toggle",
    chapter: "validate",
    route: "/simulation-baseline",
    target: "validation-timeseries-chart",
    spotlights: ["validation-metric-selector", "validation-el-nino-toggle"],
    title: "Severe Climate Context",
    body: "The El Niño overlay shades the April heat-stress period, when cooling demand and peaks spike.",
    placement: "left",
    hint: "Tick El Niño, or switch the metric.",
    media: [{
      src: IMG.elNino, variant: "card", anchor: "top-right", width: 540,
      title: "El Niño 2024 — Vietnam",
    }],
    before: [{ type: "setValidationMetric", metric: "energy" }, { type: "toggleElNino", on: true }],
  },
  {
    id: "validation-impact-metrics",
    chapter: "validate",
    route: "/simulation-baseline",
    target: "validation-summary-cards",
    title: "Operational Impact",
    body: "Less wasted energy, fewer emissions, lower grid pressure and longer asset life.",
    placement: "bottom",
  },
  {
    id: "impact-energy",
    chapter: "validate",
    route: "/simulation-baseline",
    target: "validation-delta-card",
    spotlights: ["validation-metric-selector"],
    title: "Wasted Energy, Recovered",
    body: "AI trims wasted energy in daily operation — about 8.8% fewer kWh over the recorded period.",
    placement: "bottom",
    media: [{ src: IMG.kwhBot, variant: "float", anchor: "top-left", width: 290 }],
    before: [{ type: "setValidationMetric", metric: "energy" }],
  },
  {
    id: "impact-co2",
    chapter: "validate",
    route: "/simulation-baseline",
    target: "validation-co2",
    title: "Lower Indirect Emissions",
    body: "Less energy means fewer grid emissions — CO₂ avoided is derived from the saved kWh.",
    placement: "left",
    media: [{ src: IMG.co2Bot, variant: "float", anchor: "top-right", width: 300 }],
  },
  {
    id: "impact-peak",
    chapter: "validate",
    route: "/simulation-baseline",
    target: "validation-delta-card",
    spotlights: ["validation-metric-selector"],
    title: "Relieve Peak Grid Pressure",
    body: "Flattening peaks cuts demand charges and grid stress — around 8.9% lower peak kW.",
    placement: "bottom",
    media: [{ src: IMG.peakBot, variant: "float", anchor: "top-right", width: 300 }],
    before: [{ type: "setValidationMetric", metric: "power" }],
  },
  {
    id: "impact-assets",
    chapter: "validate",
    route: "/simulation-baseline",
    target: "validation-metric-selector",
    title: "Longer Asset Life",
    body: "Smoother HVAC runtime and setpoints reduce wear — extending equipment lifespan and maintenance intervals.",
    placement: "bottom",
    media: [
      { src: IMG.expantancyBot, variant: "float", anchor: "top-center", width: 320 },
      { variant: "bubble", anchor: "top-right", width: 240, bullets: ["HVAC Device", "Electrical Load", "Sensor, Control"] },
    ],
    before: [{ type: "setValidationMetric", metric: "setpoint" }],
  },
  {
    id: "building-semantic-report",
    chapter: "validate",
    route: "/simulation-baseline",
    target: "building-semantic-report-button",
    title: "Monthly Report",
    body: "Generate a monthly performance report for review, ESG reporting or stakeholders.",
    placement: "bottom",
    blockInteraction: true,
    before: [{ type: "setValidationMetric", metric: "energy" }],
  },
  {
    id: "completion",
    chapter: "validate",
    route: "/simulation-baseline",
    title: "You've seen the GreenFlow loop",
    body: "Observe → Understand → Optimize → Validate. You're ready to explore on your own.",
    placement: "center",
  },
];

export const TUTORIAL_STEP_COUNT = tutorialSteps.length;
